%% Simulate

simRecord       = cell(nSims,1);
stateRecord     = cell(nSims,1);
parfor iSim = 1:nSims
    
    disp(strcat('Simulation ', string(iSim)));
    [mySims,simStates,retcode] = simulate(mdl, ...
        'simul_regime',             simul_regime, ...
        'simul_order',              simul_order, ...
        'simul_pruned',             simul_pruned, ...
        'simul_honor_constraints',  simul_honor_constraints, ...
        'simul_honor_constraints_through_switch', simul_honor_constraints_through_switch, ...
        'simul_anticipate_zero',    simul_anticipate_zero, ...
        'simul_periods',            simul_periods, ...
        'simul_burn',               simul_burn, ...
        'simul_frwrd_back_shoot',   simul_frwrd_back_shoot, ...
        'simul_shock_uncertainty',  simul_shock_uncertainty ...
        ); %'simul_sig',                simul_sig ...
    
    if retcode ~= 0
        decipher(retcode)
    end
    
    % Transform single vector into cell for allowing for N models
    if ~iscell(simStates)
        simStates = {simStates};
    end
    
    simRecord{iSim}     = mySims;
    stateRecord{iSim}   = simStates;
end

simRecord = horzcat(simRecord{:});