%% Compute impulse responses for all models simultaneously

myirfs = irf(M, ...
                'irf_periods', nIRFPeriods, ...
                'irf_type', irf_type, ...
                'irf_regime_specific', irf_regime_specific, ...
                'irf_draws', irf_draws, ...
                'irf_girf_regime_uncertainty', irf_girf_regime_uncertainty, ...
                'simul_regime', simul_regime, ...
                'simul_order', simul_order', ...
                'simul_pruned', simul_pruned, ...
                'simul_honor_constraints', simul_honor_constraints, ...
                'simul_honor_constraints_through_switch', simul_honor_constraints_through_switch, ...
                'simul_anticipate_zero', simul_anticipate_zero, ...
                'simul_periods', simul_periods, ...
                'simul_burn', simul_burn, ...
                'simul_frwrd_back_shoot', simul_frwrd_back_shoot, ...
                'simul_shock_uncertainty', simul_shock_uncertainty ...
                );

%%% Compute regime-specific impulse responses
%myirfs          = irf(M,'irf_periods', nIRFPeriods);