function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(7)=0;
    ys_(2)=0;
    ys_(1)=0;
    ys_(3)=0;
    ys_(5)=0;
    ys_(6)=0;
    q=0;
    ys_(8)=0;
    ys_(9)=0;
    % Auxiliary equations
ys_(10)=ys_(3);
end
